import type { SketchChallan } from "../lib/domain/types";

// Sample challans for the tests (sample roster names; the real roster lives in .env.local).
export const DEMO_CHALLANS: SketchChallan[] = [
  {
    id: "demo-1",
    productionOrderNo: "PO-106482",
    challanDate: "2026-09-23",
    draftsman: "JR\\DRAFT01",
    sketchCategory: "Scale Hard",
    sizeType: "Custom",
    developer: "DND",
    orderCount: 2,
    design: "D-8742",
    ground: "Ivory",
    border: "Indigo",
    matchingCode: "MC-118",
    quality: "Wool",
    shape: "Rectangle",
    mapWidthFt: 8.5,
    mapLengthFt: 10,
    areaSqFt: 85,
    quantity: 1,
    description: "Scale and refine the floral field and border proportions.",
    managerRemark1: "Reference image attached with the physical sample.",
    managerRemark2: "",
    sketcherRemark: "",
    dueDate: "2026-09-25",
    status: "active",
    priority: "urgent",
    createdAt: "2026-09-23T04:30:00Z",
    tasks: [
      { id: "task-1", title: "Floral field", assignedPart: "Central field and corner motifs", sketcherName: "Alpha", status: "in_progress",
        assignments: [{ id: "assignment-1", sketcherName: "Alpha", assignedOn: "2026-09-23", startedOn: "2026-09-23" }] },
      { id: "task-2", title: "Border scale", assignedPart: "Outer border and guard stripes", sketcherName: "Bravo", status: "submitted",
        assignments: [{ id: "assignment-2", sketcherName: "Bravo", assignedOn: "2026-09-23", startedOn: "2026-09-23", endedOn: "2026-09-25" }] },
    ],
    activity: [
      { id: "a1", message: "New challan received from the Excel dump.", at: "2026-09-23T04:30:00Z" },
      { id: "a2", message: "Two design-part tasks were assigned.", at: "2026-09-23T05:00:00Z" },
    ],
  },
  {
    id: "demo-2",
    productionOrderNo: "PO-106477",
    challanDate: "2026-09-22",
    draftsman: "JR\\DRAFT01",
    sketchCategory: "Border Copy paste, Bicha Scale",
    sizeType: "Runner",
    developer: "DND",
    orderCount: 1,
    design: "D-8710",
    ground: "Sand",
    border: "Rust",
    matchingCode: "MC-104",
    quality: "Wool/Viscose",
    shape: "Runner",
    mapWidthFt: 3,
    mapLengthFt: 12,
    areaSqFt: 36,
    quantity: 2,
    description: "Copy border and adjust the bicha scale for runner proportions.",
    managerRemark1: "Urgent merchant review expected.",
    managerRemark2: "",
    sketcherRemark: "",
    dueDate: "2026-09-24",
    status: "on_hold",
    priority: "high",
    createdAt: "2026-09-22T06:00:00Z",
    tasks: [
      { id: "task-3", title: "Runner composition", assignedPart: "Full runner layout", sketcherName: "Charlie", status: "blocked", blockedReason: "Waiting for clearer motif reference",
        assignments: [{ id: "assignment-3", sketcherName: "Charlie", assignedOn: "2026-09-22", startedOn: "2026-09-22" }] },
    ],
    activity: [{ id: "a3", message: "Sketching Manager placed the challan on hold.", at: "2026-09-23T07:20:00Z" }],
  },
  {
    id: "demo-3",
    productionOrderNo: "PO-106451",
    challanDate: "2026-09-20",
    draftsman: "JR\\DRAFT01",
    sketchCategory: "Copy Paste",
    sizeType: "Standard",
    developer: "DND",
    orderCount: 1,
    design: "D-8632",
    ground: "Natural",
    border: "Natural",
    matchingCode: "MC-091",
    quality: "Jute",
    shape: "Rectangle",
    mapWidthFt: 6,
    mapLengthFt: 9,
    areaSqFt: 54,
    quantity: 1,
    description: "Prepare the same copy-paste sketch for the revised order size.",
    managerRemark1: "Approved by Sketching Manager.",
    managerRemark2: "",
    sketcherRemark: "",
    dueDate: "2026-09-22",
    status: "completed",
    priority: "normal",
    createdAt: "2026-09-20T05:15:00Z",
    tasks: [{ id: "task-4", title: "Full sketch", assignedPart: "Complete design", sketcherName: "Delta", status: "completed",
      assignments: [{ id: "assignment-4", sketcherName: "Delta", assignedOn: "2026-09-20", startedOn: "2026-09-20", endedOn: "2026-09-23" }] }],
    activity: [{ id: "a4", message: "Sketching Manager approved the completed sketch.", at: "2026-09-22T10:30:00Z" }],
  },
  {
    id: "demo-4",
    productionOrderNo: "PDMAP2627/023693",
    challanDate: "2026-09-24",
    draftsman: "JR\\DRAFT01",
    sketchCategory: "Length Adjustment",
    sizeType: "Standard",
    developer: "DND",
    orderCount: 1,
    design: "THA-5009",
    ground: "Cayenne",
    border: "Stone Blue",
    matchingCode: "THA-5009-0001",
    substituteDesign: "",
    quality: "Tufted Ultra HD",
    shape: "RCT",
    mapWidthFt: 9,
    mapLengthFt: 13,
    areaSqFt: 117,
    quantity: 1,
    description: "Map RCT 9X13 Tufted Ultra HD THA-5009 Cayenne Stone Blue",
    managerRemark1: "As per JLI Master file",
    managerRemark2: "",
    sketcherRemark: "",
    dueDate: "2026-09-29",
    status: "active",
    priority: "high",
    createdAt: "2026-09-24T04:00:00Z",
    tasks: [],
    activity: [{ id: "a5", message: "New challan received.", at: "2026-09-24T04:00:00Z" }],
  },
  {
    id: "demo-5",
    productionOrderNo: "PDMAP2627/024090",
    challanDate: "2026-09-24",
    draftsman: "JR\\DRAFT01",
    sketchCategory: "Copy Paste Setting",
    sizeType: "Sample",
    developer: "DND",
    orderCount: 2,
    design: "TTWL-7005",
    ground: "White",
    border: "Forest Green",
    matchingCode: "TTWL-7005-0004",
    substituteDesign: "TTWL-7004",
    quality: "Tufted",
    shape: "Square",
    mapWidthFt: 1,
    mapLengthFt: 1,
    areaSqFt: 1,
    quantity: 2,
    description: "MAP Square 1X1 Tufted TTWL-7005 White Forest Green",
    managerRemark1: "",
    managerRemark2: "",
    sketcherRemark: "",
    dueDate: "2026-09-26",
    status: "active",
    priority: "normal",
    createdAt: "2026-09-24T05:30:00Z",
    tasks: [],
    activity: [{ id: "a6", message: "New challan received.", at: "2026-09-24T05:30:00Z" }],
  },
];
