// Full catalog of real NAV fields NOT yet in Atlas's `orders` table — verified live,
// 2026-09-12, against the actual `NAV-002 - Rug List - Main` view's
// INFORMATION_SCHEMA.COLUMNS (not guessed from the reference spreadsheet's spelling
// alone; see db/orders/021_nav_full_field_expansion.sql's header for exactly how).
// Used only by RequestColumnMenu.tsx's "Request a column" list — requesting one of
// these calls requestOrdersColumn (packages/db-management-client), which logs it in
// orders_column_requests for Ayaan to review. Direct decision, 2026-09-12: add fields
// one at a time, only the ones someone actually asks for, rather than all ~180 up
// front — see that migration's header for the full reasoning.
//
// Deliberately a plain static list, not a live DB query — this catalog only changes
// when NAV itself adds/removes a field, which is rare and worth a deliberate update
// here, not a runtime lookup.
export const REQUESTABLE_NAV_FIELDS: readonly string[] = [
  "ABC Margin",
  "Actual Branch Issue Date",
  "Actual Carpet Finish Date",
  "Actual Finishing Issue Date",
  "Actual HO Receipt Date",
  "Actual length (Ft - Inch)",
  "Actual Length (in ft)",
  "Actual Length(cms)",
  "Actual MAP Completion Date",
  "Actual Off Loom Date",
  "Actual Purchase Receipt Date",
  "Actual Repairing Issue Date",
  "Actual RPO Creation Date",
  "Actual Sq_ Ft",
  "Actual Store Issue Date",
  "Actual WareHouse Date",
  "Actual Weaver Issue Date",
  "Actual width (Ft - Inch)",
  "Actual Width (in ft)",
  "Actual Width(cms)",
  "AgingBasedOnPriorityChanged",
  "Artisan",
  "Back Order Processing Date",
  "Best Seller",
  "Border Color",
  "BR Color Family",
  "Branch Manager",
  "Bunkar Sakhi",
  "By Air",
  "Care Instruction",
  "Carpet Weight",
  "Catalog Code",
  "Center Name",
  "Collection",
  "Comment",
  "Consignee",
  "Creation User id",
  "Current Status Date",
  "Custom",
  "Customer Matching",
  "Design Group",
  "Design Inspection Remarks",
  "Design Remarks",
  "Design Status",
  "Designer",
  "Development By",
  "Due Date",
  "ETA (In Days)",
  "ETC (In Days)",
  "Exclusive Territory",
  "Exclusivity Remarks",
  "Expected Receipt Date",
  "Fiber Content",
  "Finance Code",
  "Finished Carpet Weight",
  "First Order Date",
  "First Swapped From",
  "FirstPPRDate",
  "Follow UP Team",
  "For Map Pendency",
  "Gaujratal Naama",
  "GR Color Family",
  "Gross Weight",
  "Ground Color",
  "HS Code Master",
  "Image Available",
  "India Stock Catalog",
  "Indian Design Name",
  "Intransit Location",
  "Inventory Posting Group",
  "Item Category Code",
  "Item Status For India Catalog",
  "Item Status for US Catalog",
  "JLI Sales Order No",
  "JLI SKU Ranking",
  "JLS Code JLI",
  "Job Card Printed",
  "JPR Number 878",
  "Kanni Item",
  "LeadTimeOtherPrtyinDays",
  "LeadTimeZeroPrtyinDays",
  "Licenced To",
  "Location Code",
  "Loom ID",
  "Loom Village",
  "MAP Item No_",
  "Map Planning Date",
  "MAP Production Order No_",
  "Map Serial No_",
  "Matching Status",
  "MOQ For India Catalog",
  "Mzp Status",
  "Mzp Status Date",
  "Off Loom Date for Sales",
  "Old Item Code",
  "Order Due Date",
  "Order Pack Status",
  "Order Packed Date",
  "OTN Cancelled",
  "Outdoor\\Indoor",
  "Outstanding Quantity",
  "Packed By",
  "Packing Date",
  "Packing Height",
  "Packing Length",
  "Packing Remarks",
  "Packing Width",
  "PD CAD Name",
  "Per Day Work",
  "Per Day Work For Zero Priority",
  "Pile Height in MM",
  "Planned Shipment Date",
  "PO Date",
  "Posting Date",
  "PPR Date",
  "Primary Color (Ground)",
  "Primary Pattern Code",
  "Primary Style",
  "Prod_ Cubage",
  "Prod. Item Description",
  "Product Group",
  "Product Line Category",
  "Production BOM No_",
  "Production Delivery Date",
  "Production Length",
  "Production Location",
  "Production Order Line No_",
  "Production Width",
  "Program Matching For India Cat",
  "PTN No_",
  "Purch. Item Description",
  "Purchase Due Date",
  "Purchase Order Line No_",
  "Purchase Order No_",
  "QS",
  "QS Purchase",
  "Quality Code",
  "Quality Detail",
  "Quality Group Code",
  "Quote No",
  "Rack Location",
  "Ramgarh Receipt Date",
  "Remaining Work",
  "Remarks for Production",
  "Revised Order Due Date",
  "Ring Set",
  "Running Length",
  "Sales Order Type",
  "Sample Created For",
  "Sample Info",
  "Secondary Color (Border)",
  "Secured",
  "SF Comments",
  "Shape Code",
  "Size Group",
  "Special Treatment",
  "Status",
  "Std_ Length",
  "Std_ Width",
  "StdCubageinMTR",
  "Style on Matching",
  "Sub Vendor",
  "Sub Vendor No",
  "Subcontracting Order No_",
  "Teal Project",
  "Territory Head",
  "Tufting Type",
  "Type of Business",
  "Type of Order",
  "Type of Sample",
  "TypeOfOrderChangeDt",
  "US Design Name",
  "US Matching Status",
  "Vendor Purchase",
  "Weaver",
  "Weaver Name",
  "Weaver Off Loom Date",
  "Weaver On Loom Date",
  "Weaving _ Finishing Remarks",
  "Weaving Technique",
];
